language: cpp
sudo: required
dist: trusty

os:
  - linux
  - osx
  
compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ecYol+ZudBYCt6aEqGQQBc6dvrOKr4l7P4Lo0mdtmXsrZOxAlYJK3w0wMstFY6LofpDzvsluTmL68Jt95NIP0Qvbi4ijcrr2bE6a82rgXvX/pr5LBLeh0HZ2NAgMRGNcuSsQ0gQdx0jzNsMab3vlMBgm5Yk8E6aP652HrWfUk/wSQRnB0AwwYxVH93VxmD1rnBt/E5rrMN3anMUAjPTNZ9PtUEw8taeqytOGTu002GCiCDFDhREG0lMqWqflIK/wjB95Sy9wOn+UXiL9qzUAJJoOx6ntCIQ+a5H3gX89baIsqMToOH3AqyX4suJNESmqqSb0t7udu7f4Mjn4Nx5eA5Zv/U+uFoZBjSenwu+lSmxuQhgPizLTs7K/Jid7Yw/EPa5io1NXnWWzIkFDxu4cCm83a1xxGnU/wlRYOVZNzARe4cZBUn8HD+qdYZvbqrKCxO35WNAhdvtRVc5gg+w1SeEBuCIRa8a97g96TpK9gHJvU8HUF37G/vb1iCWLUBKn6VaCrvYWhnhepHUHFWDi1SY4Tqmj+fdR8sRSdrODN7Z3hYiul/vDLmLp8gNncKbUX+LSyeUXFV7ykgN0LgbbdwYFK2wPUBIUQ6OZt6xsQk5MutZvWJnDQTMlOm00lMAReOpvAvazd062NSS/Jf6pkwK7QSkrDP09eFzcckND3ss="

addons:
  coverity_scan:
    project:
      name: "vladimirgamalian/banknote"
      description: "Build submitted via Travis CI"
    notification_email: vladimir.gamalian@gmail.com
    build_command_prepend: "cmake ."
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

script:
  - cmake .
  - make
  - ./testrunner
  
notifications:
  email: false
